version: "3"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'toDoList'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "127.0.0.1:3304:3306"
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "127.0.0.1:3002:80"
    environment:
      PMA_HOST: mysql
